In [1]:
import pandas as pd
import numpy as np
from IPython.display import display

df_ord = pd.read_csv('Orders.csv')
df_ret = pd.read_csv('Returns.csv')

In [2]:
df_ord.columns

Index(['Row.ID', 'Order.ID', 'Order.Date', 'Ship.Date', 'Ship.Mode',
       'Customer.ID', 'Customer.Name', 'Segment', 'Postal.Code', 'City',
       'State', 'Country', 'Region', 'Market', 'Product.ID', 'Category',
       'Sub.Category', 'Product.Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping.Cost', 'Order.Priority'],
      dtype='object')

In [3]:
x = ['Profit', 'Sales']

df_ord[x] = df_ord[x].apply(lambda x: x.str.replace('$', ''))
df_ord[x] = df_ord[x].apply(lambda x: x.str.replace(',', ''))
df_ord[x] = df_ord[x].astype('float64')

In [4]:
df_ord['Year'] = pd.DatetimeIndex(df_ord['Order.Date']).year

In [5]:
df_ord = df_ord.drop('Postal.Code', axis = 1)

In [6]:
df_ret.shape

(1079, 3)

In [7]:
df_ret.nunique()

Returned       1
Order ID    1079
Region        24
dtype: int64

In [8]:
df_tot = pd.merge(df_ord, df_ret, left_on = 'Order.ID', right_on = 'Order ID', how = 'left')
df_tot

,Row.ID,Order.ID,Order.Date,Ship.Date,Ship.Mode,Customer.ID,Customer.Name,Segment,City,State,...,Sales,Quantity,Discount,Profit,Shipping.Cost,Order.Priority,Year,Returned,Order ID,Region_y
0,40098,CA-2014-AB10015140-41954,11/11/14,11/13/14,First Class,AB-100151402,Aaron Bergman,Consumer,Oklahoma City,Oklahoma,...,221.98,2,0.00,62.15,40.770,High,2014,NaN,NaN,NaN
1,26341,IN-2014-JR162107-41675,2/5/14,2/7/14,Second Class,JR-162107,Justin Ritter,Corporate,Wollongong,New South Wales,...,3709.40,9,0.10,-288.77,923.630,Critical,2014,NaN,NaN,NaN
2,25330,IN-2014-CR127307-41929,10/17/14,10/18/14,First Class,CR-127307,Craig Reiter,Consumer,Brisbane,Queensland,...,5175.17,9,0.10,919.97,915.490,Medium,2014,NaN,NaN,NaN
3,13524,ES-2014-KM1637548-41667,1/28/14,1/30/14,First Class,KM-1637548,Katherine Murray,Home Office,Berlin,Berlin,...,2892.51,5,0.10,-96.54,910.160,Medium,2014,NaN,NaN,NaN
4,47221,SG-2014-RH9495111-41948,11/5/14,11/6/14,Same Day,RH-9495111,Rick Hansen,Consumer,Dakar,Dakar,...,2832.96,8,0.00,311.52,903.040,Critical,2014,NaN,NaN,NaN
5,22732,IN-2014-JM156557-41818,6/28/14,7/1/14,Second Class,JM-156557,Jim Mitchum,Corporate,Sydney,New South Wales,...,2862.68,5,0.10,763.28,897.350,Critical,2014,NaN,NaN,NaN
6,30570,IN-2012-TS2134092-41219,11/6/12,11/8/12,First Class,TS-2134092,Toby Swindell,Consumer,Porirua,Wellington,...,1822.08,4,0.00,564.84,894.770,Critical,2012,NaN,NaN,NaN
7,31192,IN-2013-MB1808592-41378,4/14/13,4/18/13,Standard Class,MB-1808592,Mick Brown,Consumer,Hamilton,Waikato,...,5244.84,6,0.00,996.48,878.380,High,2013,NaN,NaN,NaN
8,40099,CA-2014-AB10015140-41954,11/11/14,11/13/14,First Class,AB-100151402,Aaron Bergman,Consumer,Oklahoma City,Oklahoma,...,341.96,2,0.00,54.71,25.270,High,2014,NaN,NaN,NaN
9,36258,CA-2012-AB10015140-40974,3/6/12,3/7/12,First Class,AB-100151404,Aaron Bergman,Consumer,Seattle,Washington,...,48.71,1,0.20,5.48,11.130,High,2012,NaN,NaN,NaN
10,36259,CA-2012-AB10015140-40974,3/6/12,3/7/12,First Class,AB-100151404,Aaron Bergman,Consumer,Seattle,Washington,...,17.94,3,0.00,4.66,4.290,High,2012,NaN,NaN,NaN
11,28879,ID-2013-AJ107801-41383,4/19/13,4/22/13,First Class,AJ-107801,Anthony Jacobs,Corporate,Kabul,Kabul,...,4626.15,5,0.00,647.55,835.570,High,2013,NaN,NaN,NaN
12,45794,SA-2012-MM7260110-41269,12/26/12,12/28/12,Second Class,MM-7260110,Magdelene Morse,Consumer,Jizan,Jizan,...,2616.96,4,0.00,1151.40,832.410,Critical,2012,NaN,NaN,NaN
13,4132,MX-2013-VF2171518-41591,11/13/13,11/13/13,Same Day,VF-2171518,Vicky Freymann,Home Office,Toledo,Parana,...,2221.80,7,0.00,622.02,810.250,Critical,2013,NaN,NaN,NaN
14,27704,IN-2014-PF1912027-41796,6/6/14,6/8/14,Second Class,PF-1912027,Peter Fuller,Consumer,Mudanjiang,Heilongjiang,...,3701.52,12,0.00,1036.08,804.540,Critical,2014,NaN,NaN,NaN
15,13779,ES-2015-BP1118545-42216,7/31/15,8/3/15,Second Class,BP-1118545,Ben Peterman,Corporate,Paris,Ile-de-France,...,1869.59,4,0.10,186.95,801.660,Critical,2015,NaN,NaN,NaN
16,39519,CA-2012-AB10015140-40958,2/19/12,2/25/12,Standard Class,AB-100151402,Aaron Bergman,Consumer,Arlington,Texas,...,12.62,2,0.20,-2.52,1.970,Low,2012,NaN,NaN,NaN
17,12069,ES-2015-PJ1883564-42255,9/8/15,9/14/15,Standard Class,PJ-1883564,Patrick Jones,Corporate,Prato,Tuscany,...,7958.58,14,0.00,3979.08,778.320,Low,2015,NaN,NaN,NaN
18,22096,IN-2015-JS156857-42035,1/31/15,2/1/15,First Class,JS-156857,Jim Sink,Corporate,Townsville,Queensland,...,2565.59,9,0.10,28.40,766.930,Critical,2015,NaN,NaN,NaN
19,49463,TZ-2015-RH9555129-42343,12/5/15,12/7/15,Second Class,RH-9555129,Ritsa Hightower,Consumer,Uvinza,Kigoma,...,3409.74,6,0.00,818.28,763.380,High,2015,NaN,NaN,NaN
20,46630,PL-2013-AB600103-41494,8/8/13,8/10/13,First Class,AB-600103,Ann Blume,Corporate,Bytom,Silesia,...,1977.72,4,0.00,276.84,759.470,Critical,2013,NaN,NaN,NaN
21,36260,CA-2012-AB10015140-40974,3/6/12,3/7/12,First Class,AB-100151404,Aaron Bergman,Consumer,Seattle,Washington,...,242.94,3,0.00,4.86,1.280,High,2012,NaN,NaN,NaN
22,21586,IN-2012-JK1532527-41030,5/1/12,5/2/12,First Class,JK-1532527,Jason Klamczynski,Corporate,Suzhou,Anhui,...,2754.00,6,0.00,358.02,752.470,Critical,2012,NaN,NaN,NaN
23,13528,ES-2014-LB16795139-41697,2/27/14,3/1/14,Second Class,LB-16795139,Laurel Beltran,Home Office,Edinburgh,Scotland,...,5273.70,10,0.00,1898.40,730.910,High,2014,NaN,NaN,NaN
24,1570,US-2015-NP1832582-42216,7/31/15,8/1/15,First Class,NP-1832582,Naresj Patel,Consumer,Juárez,Chihuahua,...,1713.84,4,0.00,445.52,728.968,Critical,2015,NaN,NaN,NaN
25,3484,MX-2015-VD2167039-42252,9/5/15,9/8/15,First Class,VD-2167039,Valerie Dominguez,Consumer,Soyapango,San Salvador,...,2106.50,8,0.20,526.50,728.389,Critical,2015,NaN,NaN,NaN
26,30191,IN-2012-PB19210127-41259,12/16/12,12/19/12,First Class,PB-19210127,Phillip Breyer,Corporate,Taipei,Taipei City,...,1715.16,2,0.00,720.36,725.570,Critical,2012,Yes,IN-2012-PB19210127-41259,Eastern Asia
27,11645,ES-2012-EB1411048-40981,3/13/12,3/16/12,Second Class,EB-1411048,Eugene Barchas,Consumer,Leipzig,Saxony,...,3069.74,6,0.10,1364.24,725.340,Critical,2012,NaN,NaN,NaN
28,38460,CA-2012-AH10030140-41020,4/21/12,4/23/12,Second Class,AH-100301406,Aaron Hawkins,Corporate,Troy,New York,...,247.84,8,0.00,121.44,55.200,Critical,2012,NaN,NaN,NaN
29,22999,IN-2013-BP1123058-41329,2/24/13,2/24/13,Same Day,BP-1123058,Benjamin Patterson,Consumer,Surat,Gujarat,...,1878.72,4,0.00,582.36,704.080,Critical,2013,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51260,35398,US-2015-ZC21910140-42175,6/20/15,6/24/15,Standard Class,ZC-219101402,Zuschuss Carroll,Consumer,Houston,Texas,...,0.44,1,0.80,-1.11,1.010,Medium,2015,NaN,NaN,NaN
51261,35111,CA-2014-ZD21925140-41829,7/9/14,7/9/14,Same Day,ZD-219251408,Zuschuss Donatelli,Consumer,Jacksonville,Florida,...,823.96,5,0.20,51.50,69.660,Medium,2014,NaN,NaN,NaN
51262,31316,CA-2012-ZD21925140-41147,8/26/12,8/31/12,Second Class,ZD-219251404,Zuschuss Donatelli,Consumer,San Francisco,California,...,213.48,3,0.20,16.01,14.750,High,2012,NaN,NaN,NaN
51263,6367,MX-2012-BP1123082-41264,12/21/12,12/25/12,Standard Class,BP-1123082,Benjamin Patterson,Consumer,Toluca,México,...,36.48,4,0.00,3.28,1.039,Medium,2012,NaN,NaN,NaN
51264,22589,IN-2015-AO108107-42333,11/25/15,11/30/15,Standard Class,AO-108107,Anthony O'Donnell,Corporate,Perth,Western Australia,...,47.14,2,0.10,8.86,1.030,Medium,2015,NaN,NaN,NaN
51265,37195,CA-2014-ZD21925140-41733,4/4/14,4/10/14,Standard Class,ZD-219251402,Zuschuss Donatelli,Consumer,Richmond,Indiana,...,259.96,4,0.00,124.78,11.840,Medium,2014,NaN,NaN,NaN
51266,27081,ID-2013-EK13795102-41496,8/10/13,8/11/13,First Class,EK-13795102,Eileen Kiefer,Home Office,Pasig,National Capital,...,49.30,3,0.45,-18.83,1.030,Medium,2013,NaN,NaN,NaN
51267,39638,CA-2015-ZD21925140-42167,6/12/15,6/15/15,First Class,ZD-219251404,Zuschuss Donatelli,Consumer,Los Angeles,California,...,61.44,3,0.00,16.59,8.470,High,2015,NaN,NaN,NaN
51268,47274,SA-2015-JW6075110-42103,4/9/15,4/13/15,Standard Class,JW-6075110,Julia West,Consumer,Riyadh,Ar Riyad,...,5.34,1,0.00,2.16,1.030,Medium,2015,NaN,NaN,NaN
51269,15975,ES-2012-MM18055139-41038,5/9/12,5/13/12,Standard Class,MM-18055139,Michelle Moray,Consumer,Dudley,England,...,200.40,8,0.00,12.00,1.030,Medium,2012,NaN,NaN,NaN
51270,13800,ES-2015-NM1852045-42221,8/5/15,8/11/15,Standard Class,NM-1852045,Neoma Murray,Consumer,Chartres,Centre-Val de Loire,...,17.88,2,0.00,5.88,1.030,Medium,2015,NaN,NaN,NaN
51271,37194,CA-2014-ZD21925140-41733,4/4/14,4/10/14,Standard Class,ZD-219251402,Zuschuss Donatelli,Consumer,Richmond,Indiana,...,71.12,4,0.00,22.05,7.300,Medium,2014,NaN,NaN,NaN
51272,5465,MX-2015-AA1048031-42111,4/17/15,4/20/15,Second Class,AA-1048031,Andrew Allen,Consumer,San José de las Lajas,Mayabeque,...,19.32,2,0.00,0.56,1.025,Medium,2015,NaN,NaN,NaN
51273,9309,MX-2015-SL2015518-42258,9/11/15,9/12/15,First Class,SL-2015518,Sara Luxemburg,Home Office,Vespasiano,Minas Gerais,...,5.92,1,0.00,0.04,1.023,High,2015,NaN,NaN,NaN
51274,5596,MX-2014-SS2041082-41912,9/30/14,10/2/14,Second Class,SS-2041082,Shahid Shariari,Consumer,Acayucan,Veracruz,...,41.64,6,0.00,3.72,1.023,High,2014,NaN,NaN,NaN
51275,46231,ZA-2012-AS285147-40988,3/20/12,3/25/12,Standard Class,AS-285147,Alejandro Savely,Corporate,Harare,Harare,...,9.61,2,0.70,-21.17,1.020,Medium,2012,NaN,NaN,NaN
51276,31317,CA-2012-ZD21925140-41147,8/26/12,8/31/12,Second Class,ZD-219251404,Zuschuss Donatelli,Consumer,San Francisco,California,...,22.72,4,0.20,7.38,3.210,High,2012,NaN,NaN,NaN
51277,46582,TU-2015-KF6285134-42337,11/29/15,11/30/15,First Class,KF-6285134,Karen Ferguson,Home Office,Midyat,Mardin,...,34.13,6,0.60,-49.57,1.020,Medium,2015,NaN,NaN,NaN
51278,10410,ES-2012-LR1703548-41245,12/2/12,12/2/12,Same Day,LR-1703548,Lisa Ryan,Corporate,Hamburg,Hamburg,...,52.59,1,0.00,12.60,1.020,Medium,2012,NaN,NaN,NaN
51279,43818,NI-2012-PO886595-41159,9/7/12,9/9/12,Second Class,PO-886595,Patrick O'Donnell,Consumer,Lagos,Lagos,...,5.36,1,0.70,-6.46,1.020,High,2012,NaN,NaN,NaN
51280,35112,CA-2014-ZD21925140-41829,7/9/14,7/9/14,Same Day,ZD-219251408,Zuschuss Donatelli,Consumer,Jacksonville,Florida,...,15.98,2,0.20,5.00,2.010,Medium,2014,NaN,NaN,NaN
51281,6039,MX-2015-HG1502518-42164,6/9/15,6/11/15,First Class,HG-1502518,Hunter Glantz,Consumer,Bragança Paulista,São Paulo,...,84.00,5,0.00,9.20,1.019,High,2015,NaN,NaN,NaN
51282,24175,IN-2015-DB132707-42221,8/5/15,8/10/15,Standard Class,DB-132707,Deborah Brumfield,Home Office,Townsville,Queensland,...,58.05,5,0.10,19.95,1.010,Medium,2015,NaN,NaN,NaN
51283,24105,IN-2015-KH1633058-42154,5/30/15,5/30/15,Same Day,KH-1633058,Katharine Harms,Corporate,Lucknow,Uttar Pradesh,...,26.94,2,0.00,1.86,1.010,High,2015,NaN,NaN,NaN
51284,9922,MX-2013-KM1637593-41636,12/28/13,12/31/13,First Class,KM-1637593,Katherine Murray,Home Office,Managua,Managua,...,18.64,1,0.00,8.00,1.010,Medium,2013,NaN,NaN,NaN
51285,29002,IN-2015-KE1642066-42174,6/19/15,6/19/15,Same Day,KE-1642066,Katrina Edelman,Corporate,Kure,Hiroshima,...,65.10,5,0.00,4.50,1.010,Medium,2015,NaN,NaN,NaN
51286,34337,US-2014-ZD21925140-41765,5/6/14,5/10/14,Standard Class,ZD-219251408,Zuschuss Donatelli,Consumer,Chattanooga,Tennessee,...,16.72,5,0.20,3.34,1.930,High,2014,NaN,NaN,NaN
51287,31315,CA-2012-ZD21925140-41147,8/26/12,8/31/12,Second Class,ZD-219251404,Zuschuss Donatelli,Consumer,San Francisco,California,...,8.56,2,0.00,2.48,1.580,High,2012,NaN,NaN,NaN
51288,9596,MX-2013-RB1979518-41322,2/17/13,2/21/13,Standard Class,RB-1979518,Ross Baird,Home Office,Valinhos,São Paulo,...,13.44,2,0.00,2.40,1.003,Medium,2013,NaN,NaN,NaN
51289,6147,MX-2013-MC1810093-41416,5/22/13,5/26/13,Second Class,MC-1810093,Mick Crebagga,Consumer,Tipitapa,Managua,...,61.38,3,0.00,1.80,1.002,High,2013,NaN,NaN,NaN

In [9]:
df_tot = df_tot.rename(index = str, columns = {'Region_x': 'Region'})

In [10]:
df_tot = df_tot.drop(['Order ID', 'Region_y'], axis = 1)
df_tot[df_tot.Returned.isnull()] = ''

In [11]:
df_tot.columns

Index(['Row.ID', 'Order.ID', 'Order.Date', 'Ship.Date', 'Ship.Mode',
       'Customer.ID', 'Customer.Name', 'Segment', 'City', 'State', 'Country',
       'Region', 'Market', 'Product.ID', 'Category', 'Sub.Category',
       'Product.Name', 'Sales', 'Quantity', 'Discount', 'Profit',
       'Shipping.Cost', 'Order.Priority', 'Year', 'Returned'],
      dtype='object')

In [12]:
#3.1
df_tot[df_tot.Returned == 'Yes'].groupby('Year').agg({'Sales':'sum'})

          Sales
Year
2012  111935.81
2013   96575.21
2014  133737.41
2015  183683.98

In [13]:
#3.2
x = df_tot[df_tot.Returned == 'Yes'].groupby('Customer.ID').agg({'Sales':'count'})
print('More than 1 Return: ', len(x[x.Sales > 1]))
print('More than 5 Return: ', len(x[x.Sales > 5]))

More than 1 Return:  547
More than 5 Return:  46

In [14]:
#3.3
df_tot[df_tot.Returned == 'Yes'].groupby('Region').agg({'Sales':'count'}).sort_values(by = 'Sales', ascending = False)

                   Sales
Region
Central America      248
Western Europe       233
Western US           177
Oceania              154
Southeastern Asia    140
Eastern US           134
South America        133
Eastern Asia         131
Southern Europe      112
Southern Asia        111
Western Asia         108
Southern US           83
Northern Europe       76
Central US            74
Caribbean             69
Western Africa        60
North Africa          51
Eastern Europe        42
Southern Africa       25
Eastern Africa        18
Central Africa        17
Canada                15
Central Asia           9

In [15]:
#3.4
df_tot[df_tot.Returned == 'Yes'].groupby('Sub.Category').agg({'Sales':'count'}).sort_values(by = 'Sales', ascending = False)

              Sales
Sub.Category
Binders         269
Art             217
Storage         212
Paper           150
Chairs          147
Phones          145
Accessories     138
Labels          137
Furnishings     135
Bookcases       104
Supplies        103
Fasteners       102
Envelopes        99
Copiers          99
Machines         63
Appliances       59
Tables           41